name: "Bug Report"
description: "Report a bug with the product"
title: "[BUG] "
labels: "bug"
body:
- type: dropdown
  id: plaform
  attributes:
    label: "Platform"
    description: "What platform are you playing the game on?"
    multiple: false
    options: 
      - Newgrounds (Web/HTML5)
      - Itch.io (Web/HTML5)
      - Windows
      - Compiled
  validations:
    required: true
- type: input
  id: browser
  attributes:
    label: "Browser (Web Only)"
    description: "For users on web, what browser are you on?"
    placeholder: "The sponsor of todays video Opera GX"
  validations:
    required: false
- type: input
  id: version
  attributes:
    label: "Game version"
    description: "The current game version, you can use the main menu to see what your version is"
    placeholder: "3.00 Pre-Release 3"
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: "Description"
    description: "Describe the bug"
    value: |
      N / A
  validations:
    required: true
